@startuml
hide empty members
skinparam classAttributeIconSize 0
title Ontology Class Diagram
class Company {
}
class ConceptualElement {
  Name : string
}
class Contractor {
}
class Employee {
}
class Person {
  name : string
}
class Requirement {
  Id : string
  text : string
}
Employee --|> Person
Contractor --|> Person
Employee -- "1" Company : worksFor
Requirement -- "*" Requirement : derivedReq
ConceptualElement -- "*" ConceptualElement : association
Requirement -- "*" ConceptualElement : satisfy
Employee -- "1" Company : worksFor
note "Company ⟂ ConceptualElement" as N1
Company .. N1
ConceptualElement .. N1
note "Company ⟂ Requirement" as N2
Company .. N2
Requirement .. N2
note "Contractor ⟂ ConceptualElement" as N3
Contractor .. N3
ConceptualElement .. N3
note "Employee ⟂ ConceptualElement" as N4
Employee .. N4
ConceptualElement .. N4
note "Person ⟂ ConceptualElement" as N5
Person .. N5
ConceptualElement .. N5
note "Requirement ⟂ ConceptualElement" as N6
Requirement .. N6
ConceptualElement .. N6
note "Employee ⟂ Contractor" as N7
Employee .. N7
Contractor .. N7
note "Contractor ⟂ Requirement" as N8
Contractor .. N8
Requirement .. N8
note "Employee ⟂ Requirement" as N9
Employee .. N9
Requirement .. N9
note "Person ⟂ Requirement" as N10
Person .. N10
Requirement .. N10
@enduml